---
title: "LETR Sites"
author: "Nathaniel Burola, Karan Shetty, Priscilla Hare"
date: "November 13, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
#need to install lmtest package in order to install vcdExtra packages

library(tidyverse)
library(vcdExtra)
library(kableExtra)
library(gmodels)
library(car)
library(onewaytests)


```

```{r, include=FALSE}
lobster_size <- read_csv("lobster_size_abundance.csv")
lobster_trap <- read_csv("lobster_traps.csv")

```


```{r}
#Make the counts in the lobster size table in tidy format

lobster_size_tidy <- as.data.frame(lobster_size) %>% 
  filter(size != "-99999") %>% 
  expand.dft(freq = "count")

```

```{r}

carp_traps <- lobster_trap %>% 
  filter(site == "CARP") %>% 
  select("year","site", "traps") %>% 
  group_by(year) %>% 
  summarize("CARP traps" = sum(traps)) 

aque_traps <- lobster_trap %>% 
  filter(site == "AQUE") %>% 
  select("year","site", "traps") %>% 
  group_by(year) %>% 
  summarize("AQUE traps" = sum(traps)) 
  
sizeCARP <- lobster_size_tidy %>% 
  filter(site == "CARP") %>% 
  select("year","site", "size") %>% 
  group_by(year) %>% 
  summarize(number = n()) 


CARPmerge <- merge(carp_traps, sizeCARP, by = "year")




```

```{r}
#Making graphs of counts at each site each year for lobsters 

lobster_count<-lobster_size_tidy %>% 
  select("year", "site", "size") %>% 
  group_by(year) %>% 
  count(site) 

 
abundance <- lobster_count %>% 
  ggplot(aes(x = year, y = n))+
  geom_col()+
  facet_wrap(~site)
abundance

```


```{r}

#graphs of avg counts for  traps


trap_count<-lobster_trap %>% 
  filter(site == "AQUE" | site == "CARP" | site == "IVEE" | site == "MOHK" |site == "NAPL") %>% 
  select("year", "site", "traps", "date") %>% 
  group_by(year, site, date) %>% 
  summarize("traps" = sum(traps)) 

#trap_graph <- trap_count %>% 
  #ggplot(aes(x = year, y = traps)) +
  #geom_col()+
  #facet_wrap(~site)
#trap_graph

#uses mean trap from surveys each year USE THIS INSTEAD OF TOTAL COUNTS ABOVE
trap_avg <- trap_count %>% 
  group_by(year, site) %>% 
  summarize(mean = mean(traps))

trap_graph_avg <- trap_avg %>% 
  ggplot(aes(x = year, y = mean)) +
  geom_col()+
  facet_wrap(~site)
trap_graph_avg




```

```{r}
#makes a graph comparing lobsters and traps

lobster_count2 <- as.data.frame(lobster_count) %>% 
  mutate(row = seq(1,30, by = 1))

trap_avg2 <- as.data.frame(trap_avg) %>% 
  mutate(row = seq(1,30, by =1))



lobster_trap_combine <- left_join(lobster_count2, trap_avg2, by = 'row')

comp_graph <- lobster_trap_combine %>% 
  ggplot(aes(x = year.x, y = n))+
  geom_point() +
  geom_point(aes(x = year.x, y = mean, color = 'red'))+
  facet_wrap(~site.x, scales = "free")

comp_graph
```


```{r}
#Part 2

lobster_17 <- lobster_size_tidy %>% 
  filter(year == 2017)

lobster_17_summary <- lobster_17 %>% 
  group_by(site) %>% 
  summarize(mean = mean(size), n = n(), sd = sd(size))

#exploratory hist
hists <- ggplot(lobster_17, aes(x = size)) +
  geom_histogram(aes(fill = site)) +
  facet_wrap(~site, scale = "free")

hists

qq <- ggplot(lobster_17, aes(sample = size)) +
  geom_qq(aes(color = site)) +
  facet_wrap(~site, scale = "free")

qq

# Based on qq plots and histograms, observations for each group appear normally distrubuted, also n>30 for all groups so means will be normally distributed by central limit theorem

#Now test for equal variance
# If the largest sample variances is < 4x greater than the smallest samople variance, then these are close enough to consider variances equal

variances <- lobster_17 %>% 
  group_by(site) %>% 
  summarize(
    variance = var(size)
  )

variances #the largest variance (205) is definitely not more than 4x greater than smallest variacne (86)

#formal hypothesis test for equal variances - Levenes test
# leveneTest() function in the 'car' package

#H0: no difference in variacnes
#HA: difference in variances

levene_lobster <- leveneTest(size ~ site, data = lobster_17)

levene_lobster

#p < .05 so we would conclude that the variances are different but from previous test of largest variance being less than 4x smallest variances we can still assume equal variacnes

#now ANOVA
#H0: means across all groups are equal
#HA: at least 2 means differ

lobster_aov <- aov(size ~ site, data = lobster_17)

summary(lobster_aov)

#Post-hoc testing by Tukey's HSD
#H0: there is no significant difference in pair wise means
#HA: there is a significant difference in pair wise means
lobster_post <- TukeyHSD(lobster_aov)
lobster_post
#only NAPL and IVEE differ significantly but differ vy less than 5mm





#create a column graph with error bars for means of each month
lobster_17_graph <- ggplot(lobster_17, aes(x = site, y = size)) + 
  geom_boxplot(outlier.size = NA) +
  #geom_errorbar(aes(ymin = mean-sd, ymax = mean+sd, width = .3)) + #edits width of error bars
  theme_classic() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) + #rotates x axis labels
  labs(x = "Site", y = "Mean Lobster Size (carapace length (mm))", title = "Lobster sizes in the Santa Barabara Chanel (2017)") +
  theme(text = element_text(family = "Times New Roman")) + 
  theme(plot.title = element_text(hjust = 0.5, size = 13)) +
  theme(plot.subtitle = element_text(hjust = 0.5, size = 10)) +
  theme(axis.title = element_text(size = 12), axis.text = element_text(size = 10)) 
  #scale_y_continuous(expand = c(0,0))  #edits y axis scale and brings it down to be flush with the x axis
  #edits y axis scale and brings it down to be flush with the x axis

lobster_17_graph

lobster_17_graph + 
  annotate("text", x = 1, y = 110, label = "ab", size = 3) +
  annotate("text", x = 2, y = 110, label = "ab", size = 3) +
  annotate("text", x = 3, y = 110, label = "a", size = 3) +
  annotate("text", x = 4, y = 99, label = "ab", size = 3) +
  annotate("text", x = 5, y = 110, label = "b", size = 3)
```



```{r}
# Part 3: Changes in lobster size between MPA and non-MPA sites

lobster_size_2012 = lobster_size_tidy %>%
  group_by(site, year) %>%
  select(year, site, size) %>% 
  filter(year == "2012")

lobster_size_2012

lobster_bar_2012 = ggplot(lobster_size_2012, aes(x = size))  +
  geom_bar(aes(color = site)) +
  facet_wrap(~ site) +
  xlab("Year") +
  ylab("Lobster size")

lobster_bar_2012

# same but for 2017
lobster_size_2017 = lobster_size_tidy %>% 
  group_by(site, year) %>% 
  select(year, site, size) %>% 
  filter(year == "2017")

lobster_bar_2017 = ggplot(lobster_size_2017, aes(x = size))  +
  geom_bar(aes(color = site)) +
  facet_wrap(~ site) +
  xlab("Year") +
  ylab("Lobster size")


lobster_bar_2017

# Created a bar graph displaying size counts across all five sites for 2012 and 2017. WIP



```

```{r}
# Comparison of individual sites (both MPAs and non-MPAs) for lobster counts and sizes from 2012 and from 2017.

# MPAs first: IVEE

IV_2012 = lobster_size_2012 %>% 
  filter(site == "IVEE") %>%
  ungroup(site, year) %>% 
  pull(size)

IV_2017 = lobster_size_2017 %>% 
  filter(site == "IVEE") %>%
  ungroup(site, year) %>% 
  pull(size)

IV_combined = lobster_size_tidy %>% 
  filter(site == "IVEE") %>% 
  group_by(year) %>% 
  filter(year == "2012" | year == "2017") %>% 
  select(year, size)

IV_hist = ggplot(IV_combined, aes(x = size)) +
  geom_histogram(aes(fill = year), show.legend = FALSE) +
  facet_wrap(~ year) +
  labs(y = "Frequency", x = "Size (mm)", title = "Lobster size frequency at Isla Vista MPA in 2012 and 2017")

IV_hist

IV_qq = ggplot(IV_combined, aes(sample = size)) +
  geom_qq(aes(color = year), show.legend = FALSE) +
  facet_wrap(~ year, scale = "free")

IV_qq

f_test_iv = var.test(IV_2012, IV_2017)


f_test_iv

t_test_iv = t.test(IV_2012, IV_2017, var.equal = TRUE)

t_test_iv # ignore this, this might be wrong. this is measuring true difference in size when I think it should be difference in counts
#i think it should be size - Priscilla


IV_wilcox = wilcox.test(IV_2012, IV_2017)

# MPA 2: NAPL

npl_2012 = lobster_size_2012 %>% 
  filter(site == "NAPL") %>% 
  ungroup(site, year) %>% 
  pull(size)

npl_2017 = lobster_size_2017 %>% 
  filter(site == "NAPL") %>% 
  ungroup(site, year) %>% 
  pull(size)

npl_combined = lobster_size_tidy %>% 
  filter(site == "NAPL") %>% 
  group_by(year) %>% 
  filter(year == "2012" | year == "2017") %>% 
  select(year, size)

npl_hist = ggplot(npl_combined, aes(x = size)) +
  geom_histogram(aes(fill = year), show.legend = FALSE) +
  facet_wrap(~ year) +
  labs(y = "Frequency", x = "Size (mm)", title = "Lobster size frequency at Naples MPA in 2012 and 2017")

npl_hist

npl_qq = ggplot(npl_combined, aes(sample = size)) +
  geom_qq(aes(color = year), show.legend = FALSE) +
  facet_wrap(~ year, scale = "free")

npl_qq

t_test_npl = t.test(npl_2012, npl_2017, var.equal = TRUE)
t_test_npl


npl_wilcox = wilcox.test(npl_2012, npl_2017)
npl_wilcox

```

```{r}

# Doing the same for the non-MPA sites

# AQUE

aq_2012 = lobster_size_2012 %>% 
  filter(site == "AQUE") %>%
  ungroup(site, year) %>% 
  pull(size)

aq_2017 = lobster_size_2017 %>% 
  filter(site == "AQUE") %>% 
  ungroup(site, year) %>% 
  pull(size)

aq_combined = lobster_size_tidy %>% 
  filter(site == "AQUE") %>% 
  group_by(year) %>% 
  filter(year == "2012" | year == "2017") %>% 
  select(year, size)

aq_hist = ggplot(aq_combined, aes(x = size)) +
  geom_histogram(aes(fill = year), show.legend = FALSE) +
  facet_wrap(~ year) +
  labs(y = "Frequency", x = "Size (mm)")
aq_hist

f_test_aq = var.test(aq_2012, aq_2017)
f_test_aq

t_test_aq = t.test(aq_2012, aq_2017, var.equal = TRUE)
t_test_aq

aq_mannw = wilcox.test(aq_2012, aq_2017)
aq_mannw


# CARP

ca_2012 = lobster_size_2012 %>% 
  filter(site == "CARP") %>%
  ungroup(site, year) %>% 
  pull(size)

ca_2017 = lobster_size_2017 %>% 
  filter(site == "CARP") %>% 
  ungroup(site, year) %>% 
  pull(size)

ca_combined = lobster_size_tidy %>% 
  filter(site == "CARP") %>% 
  group_by(year) %>% 
  filter(year == "2012" | year == "2017") %>% 
  select(year, size)

ca_hist = ggplot(ca_combined, aes(x = size)) +
  geom_histogram(aes(fill = year), show.legend = FALSE) +
  facet_wrap(~ year) +
  labs(y = "Frequency", x = "Size (mm)")
ca_hist

f_test_ca = var.test(ca_2012, ca_2017)
f_test_ca

t_test_ca = t.test(ca_2012, ca_2017, var.equal = TRUE)
t_test_ca


ca_mannw = wilcox.test(ca_2012, ca_2017)
ca_mannw



```
















```{r}
#Part 4: Proportions of legal (over 82.6mm) lobster sizes for each site

#create a table of counts for legal and illegal sizes
legal_lobster<-lobster_size_tidy %>% 
  filter(year == "2017") %>% 
  mutate(
    legal = case_when(
      size >= 82.6 ~ "legal",
      size < 82.6 ~ "illegal"
    )
  ) %>% 
  select("site", "size", "legal") %>% 
  group_by(site) %>% 
  count(legal) 
  

#spread the table to put in the format of a contingency table
legal_lobster2 <- as.data.frame(legal_lobster) %>% 
  spread(legal, n) 

legal_lobster3 <- legal_lobster2 %>% 
  select(-site)

rownames(legal_lobster3) <- c("AQUE", "CARP", "IVEE", "MOHK", "NAPL")

#create a table of proportions
legal_prop <- prop.table(as.matrix(legal_lobster3), 1)

legal_prop2 <- as.data.frame(legal_prop) %>% 
  mutate(site = c("AQUE", "CARP", "IVEE", "MOHK", "NAPL")) %>% 
  select("site", "illegal", "legal")


#combines counts and proportions but not neat
#legal_matrix <- as.matrix(legal_lobster3)
#count_prop <- CrossTable(legal_matrix, digits = 3, prop.r = TRUE, prop.c = FALSE, prop.t = FALSE, prop.chisq = FALSE)
#count_prop

#making a joined table
legal_count_prop <- left_join(legal_lobster2, legal_prop2, by = 'site') %>% 
  select("site", "legal.x", "legal.y", "illegal.x", "illegal.y") %>% 
  mutate(legal_prop = round(legal.y, 3),
         illegal_prop = round(illegal.y, 3),
         site = c("Arroyo Quemado", "Carpinteria", "Isla Vista", "Mohawk Reef", "Naples Reef" ))

#making the table pretty  
count_prop_table <- kable(
  legal_count_prop, 
  align = c('r', 'c', 'c', 'c', 'c', 'c'), #alligns the first column left, and all subsequent columns centered
  col.names = c(" ", "Count", "Proportion", "Count", "Proportion"), 
  caption = "Table x: insert description and chi-square test results here)." 
  )  %>%  
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = FALSE, font_size = 12) %>% 
  add_header_above(c(" ", "Legal" = 2, "Illegal" = 2)) %>%
  column_spec(1, bold = TRUE, color = "navy", width = "3cm")

count_prop_table

#run a chi square test on the table of counts
legal_x2 <- chisq.test(legal_lobster3)
legal_x2
legal_x2$stdres

lobster_prop_for_graph <- legal_lobster2 %>% 
  mutate(
    total = illegal + legal
  ) %>% 
  mutate(
    prop_legal = legal/total
  )

prop_grpah<- as.data.frame(lobster_prop_for_graph) %>% 
  ggplot(aes(x = site, y = prop_legal)) +
  geom_col()

prop_graph
```

